version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
    networks:
      - mynetwork

networks:
  mynetwork:
